/**
 * lib/sample-timeline.ts — Fallback timeline data for sample stories.
 *
 * Used when the API is not available (local dev without Supabase).
 * Keyed by sample story ID (a1–a6) matching sampleArticles in sample-data.ts.
 */

import type { StoryTimeline } from '@/lib/types'

export const sampleTimelines: Record<string, StoryTimeline> = {
  a1: {
    storyId: 'a1',
    totalArticles: 43,
    timeSpanHours: 72,
    events: [
      {
        id: 'a1-evt-0',
        timestamp: '2026-02-27T08:00:00Z',
        kind: 'source-added',
        sourceName: 'Reuters',
        sourceBias: 'center',
        description: 'Reuters began covering this story',
        cumulativeSourceCount: 1,
        cumulativeSpectrum: [{ bias: 'center', percentage: 100 }],
      },
      {
        id: 'a1-evt-1',
        timestamp: '2026-02-27T10:30:00Z',
        kind: 'source-added',
        sourceName: 'The Guardian',
        sourceBias: 'left',
        description: 'The Guardian began covering this story',
        cumulativeSourceCount: 2,
        cumulativeSpectrum: [
          { bias: 'left', percentage: 50 },
          { bias: 'center', percentage: 50 },
        ],
      },
      {
        id: 'a1-evt-2',
        timestamp: '2026-02-28T06:00:00Z',
        kind: 'spectrum-shift',
        sourceName: 'New York Times',
        sourceBias: 'lean-left',
        description: 'Coverage spectrum shifted significantly',
        cumulativeSourceCount: 4,
        cumulativeSpectrum: [
          { bias: 'left', percentage: 25 },
          { bias: 'lean-left', percentage: 50 },
          { bias: 'center', percentage: 25 },
        ],
      },
      {
        id: 'a1-evt-3',
        timestamp: '2026-02-28T14:00:00Z',
        kind: 'milestone',
        sourceName: 'Wall Street Journal',
        sourceBias: 'lean-right',
        description: '5 sources now covering this story',
        cumulativeSourceCount: 5,
        cumulativeSpectrum: [
          { bias: 'left', percentage: 20 },
          { bias: 'lean-left', percentage: 40 },
          { bias: 'center', percentage: 20 },
          { bias: 'lean-right', percentage: 20 },
        ],
      },
      {
        id: 'a1-evt-4',
        timestamp: '2026-03-01T08:00:00Z',
        kind: 'milestone',
        sourceName: 'NPR',
        sourceBias: 'lean-left',
        description: '10 sources now covering this story',
        cumulativeSourceCount: 10,
        cumulativeSpectrum: [
          { bias: 'far-left', percentage: 5 },
          { bias: 'left', percentage: 22 },
          { bias: 'lean-left', percentage: 28 },
          { bias: 'center', percentage: 25 },
          { bias: 'lean-right', percentage: 14 },
          { bias: 'right', percentage: 6 },
        ],
      },
    ],
  },
  a2: {
    storyId: 'a2',
    totalArticles: 67,
    timeSpanHours: 48,
    events: [
      {
        id: 'a2-evt-0',
        timestamp: '2026-02-26T14:30:00Z',
        kind: 'source-added',
        sourceName: 'AP News',
        sourceBias: 'center',
        description: 'AP News began covering this story',
        cumulativeSourceCount: 1,
        cumulativeSpectrum: [{ bias: 'center', percentage: 100 }],
      },
      {
        id: 'a2-evt-1',
        timestamp: '2026-02-27T09:00:00Z',
        kind: 'source-added',
        sourceName: 'Wall Street Journal',
        sourceBias: 'lean-right',
        description: 'Wall Street Journal began covering this story',
        cumulativeSourceCount: 3,
        cumulativeSpectrum: [
          { bias: 'center', percentage: 40 },
          { bias: 'lean-right', percentage: 30 },
          { bias: 'lean-left', percentage: 30 },
        ],
      },
      {
        id: 'a2-evt-2',
        timestamp: '2026-02-28T14:30:00Z',
        kind: 'milestone',
        sourceName: 'The Economist',
        sourceBias: 'lean-right',
        description: '10 sources now covering this story',
        cumulativeSourceCount: 10,
        cumulativeSpectrum: [
          { bias: 'left', percentage: 15 },
          { bias: 'lean-left', percentage: 20 },
          { bias: 'center', percentage: 35 },
          { bias: 'lean-right', percentage: 22 },
          { bias: 'right', percentage: 8 },
        ],
      },
    ],
  },
  a3: {
    storyId: 'a3',
    totalArticles: 31,
    timeSpanHours: 36,
    events: [
      {
        id: 'a3-evt-0',
        timestamp: '2026-02-26T11:15:00Z',
        kind: 'source-added',
        sourceName: 'BBC News',
        sourceBias: 'center',
        description: 'BBC News began covering this story',
        cumulativeSourceCount: 1,
        cumulativeSpectrum: [{ bias: 'center', percentage: 100 }],
      },
      {
        id: 'a3-evt-1',
        timestamp: '2026-02-27T08:00:00Z',
        kind: 'milestone',
        sourceName: 'New York Times',
        sourceBias: 'lean-left',
        description: '5 sources now covering this story',
        cumulativeSourceCount: 5,
        cumulativeSpectrum: [
          { bias: 'lean-left', percentage: 40 },
          { bias: 'center', percentage: 40 },
          { bias: 'lean-right', percentage: 20 },
        ],
      },
    ],
  },
  a4: {
    storyId: 'a4',
    totalArticles: 28,
    timeSpanHours: 24,
    events: [
      {
        id: 'a4-evt-0',
        timestamp: '2026-02-25T09:45:00Z',
        kind: 'source-added',
        sourceName: 'The Guardian',
        sourceBias: 'left',
        description: 'The Guardian began covering this story',
        cumulativeSourceCount: 1,
        cumulativeSpectrum: [{ bias: 'left', percentage: 100 }],
      },
      {
        id: 'a4-evt-1',
        timestamp: '2026-02-26T02:00:00Z',
        kind: 'spectrum-shift',
        sourceName: 'New York Times',
        sourceBias: 'lean-left',
        description: 'Coverage spectrum shifted significantly',
        cumulativeSourceCount: 4,
        cumulativeSpectrum: [
          { bias: 'left', percentage: 50 },
          { bias: 'lean-left', percentage: 50 },
        ],
      },
      {
        id: 'a4-evt-2',
        timestamp: '2026-02-26T09:45:00Z',
        kind: 'milestone',
        sourceName: 'Washington Post',
        sourceBias: 'lean-left',
        description: '5 sources now covering this story',
        cumulativeSourceCount: 5,
        cumulativeSpectrum: [
          { bias: 'far-left', percentage: 8 },
          { bias: 'left', percentage: 35 },
          { bias: 'lean-left', percentage: 40 },
          { bias: 'center', percentage: 12 },
          { bias: 'lean-right', percentage: 5 },
        ],
      },
    ],
  },
  a5: {
    storyId: 'a5',
    totalArticles: 89,
    timeSpanHours: 60,
    events: [
      {
        id: 'a5-evt-0',
        timestamp: '2026-02-23T16:00:00Z',
        kind: 'source-added',
        sourceName: 'Reuters',
        sourceBias: 'center',
        description: 'Reuters began covering this story',
        cumulativeSourceCount: 1,
        cumulativeSpectrum: [{ bias: 'center', percentage: 100 }],
      },
      {
        id: 'a5-evt-1',
        timestamp: '2026-02-24T10:00:00Z',
        kind: 'milestone',
        sourceName: 'NPR',
        sourceBias: 'lean-left',
        description: '5 sources now covering this story',
        cumulativeSourceCount: 5,
        cumulativeSpectrum: [
          { bias: 'lean-left', percentage: 30 },
          { bias: 'center', percentage: 40 },
          { bias: 'lean-right', percentage: 30 },
        ],
      },
      {
        id: 'a5-evt-2',
        timestamp: '2026-02-25T16:00:00Z',
        kind: 'milestone',
        sourceName: 'Fox News',
        sourceBias: 'right',
        description: '10 sources now covering this story',
        cumulativeSourceCount: 10,
        cumulativeSpectrum: [
          { bias: 'left', percentage: 20 },
          { bias: 'lean-left', percentage: 25 },
          { bias: 'center', percentage: 30 },
          { bias: 'lean-right', percentage: 18 },
          { bias: 'right', percentage: 7 },
        ],
      },
    ],
  },
  a6: {
    storyId: 'a6',
    totalArticles: 52,
    timeSpanHours: 44,
    events: [
      {
        id: 'a6-evt-0',
        timestamp: '2026-02-22T07:30:00Z',
        kind: 'source-added',
        sourceName: 'BBC News',
        sourceBias: 'center',
        description: 'BBC News began covering this story',
        cumulativeSourceCount: 1,
        cumulativeSpectrum: [{ bias: 'center', percentage: 100 }],
      },
      {
        id: 'a6-evt-1',
        timestamp: '2026-02-23T12:00:00Z',
        kind: 'milestone',
        sourceName: 'MSNBC',
        sourceBias: 'left',
        description: '5 sources now covering this story',
        cumulativeSourceCount: 5,
        cumulativeSpectrum: [
          { bias: 'left', percentage: 20 },
          { bias: 'lean-left', percentage: 30 },
          { bias: 'center', percentage: 35 },
          { bias: 'lean-right', percentage: 15 },
        ],
      },
    ],
  },
}
