/**
 * app/api/events/story/route.ts — Telemetry ingest for story_views.
 *
 * Accepts a single engagement event (view / dwell / read_through / share)
 * and inserts it via the service-role client. Privacy guarantees enforced
 * here, before the row reaches the DB:
 *
 *   - DNT short-circuit: if the request includes `DNT: 1`, we drop the
 *     event silently with 204. The client should not send anyway, but
 *     the server is the last line of defense.
 *   - Session id: read from `axiom_session` cookie (web) or `x-session-id`
 *     header (mobile). If neither is present we drop with 204 — without a
 *     session id we can't dedupe and would pollute uniqueViewers metrics.
 *   - User id: looked up via cookie or Bearer auth. Optional; anonymous
 *     events are first-class citizens.
 *
 * Service-role client is used for the INSERT because RLS allows anon
 * insert by policy, but going through the service key avoids tying the
 * event row to whatever auth.uid() the request happens to carry — it
 * keeps the user_id column under our control (we only set it when we
 * intend to attribute, never as a side-effect of the auth context).
 */

import { NextRequest, NextResponse } from 'next/server'
import { cookies, headers } from 'next/headers'
import { getSupabaseServiceClient } from '@/lib/supabase/server'
import { getAuthenticatedUser } from '@/lib/api/auth-helpers'
import { storyViewEventSchema } from '@/lib/api/telemetry-validation'
import { insertStoryViewEvent } from '@/lib/api/engagement-queries'

const SESSION_COOKIE_NAME = 'axiom_session'
const SESSION_HEADER_NAME = 'x-session-id'
// Mirror of the UUID v4-ish format generated by middleware (web cookie)
// and apps/mobile/lib/hooks/use-session-id (mobile header). Validating
// shape here is defense in depth: it rejects junk/empty/scripted ids
// that don't even match the format we issue, before they pollute
// `unique_viewers_6h` reads in Hot Now / trending. It does NOT stop a
// scripted attacker who mints valid UUIDs — that requires HMAC + per-IP
// rate limiting (deferred per docs/phase3-privacy-audit.md).
const SESSION_ID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i

const NO_STORE_HEADERS = { 'Cache-Control': 'no-store' } as const

function dropped(): NextResponse {
  return new NextResponse(null, { status: 204, headers: NO_STORE_HEADERS })
}

export async function POST(request: NextRequest) {
  const headerStore = await headers()
  if (headerStore.get('dnt') === '1') return dropped()

  let body: unknown
  try {
    body = await request.json()
  } catch {
    return NextResponse.json(
      { success: false, error: 'Invalid JSON body' },
      { status: 400, headers: NO_STORE_HEADERS }
    )
  }

  const parsed = storyViewEventSchema.safeParse(body)
  if (!parsed.success) {
    return NextResponse.json(
      { success: false, error: parsed.error.issues.map((i) => i.message).join('; ') },
      { status: 400, headers: NO_STORE_HEADERS }
    )
  }

  const cookieStore = await cookies()
  const sessionId =
    cookieStore.get(SESSION_COOKIE_NAME)?.value ?? headerStore.get(SESSION_HEADER_NAME) ?? null

  if (!sessionId || !SESSION_ID_REGEX.test(sessionId)) return dropped()

  // Best-effort user attribution — failure to resolve a user is normal
  // (anonymous traffic) and must not abort the event.
  let userId: string | null = null
  try {
    const { user } = await getAuthenticatedUser()
    userId = user?.id ?? null
  } catch {
    userId = null
  }

  const service = getSupabaseServiceClient()
  try {
    await insertStoryViewEvent(service, {
      story_id: parsed.data.storyId,
      user_id: userId,
      session_id: sessionId,
      action: parsed.data.action,
      dwell_bucket: parsed.data.dwellBucket ?? null,
      referrer_kind: parsed.data.referrerKind ?? null,
      client: parsed.data.client,
    })
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Internal server error'
    return NextResponse.json(
      { success: false, error: message },
      { status: 500, headers: NO_STORE_HEADERS }
    )
  }

  return new NextResponse(null, { status: 204, headers: NO_STORE_HEADERS })
}
