/**
 * lib/supabase/seed-sources.ts — Seed data for the sources table.
 *
 * 55 news outlets with bias, factuality, ownership, and RSS feed URLs.
 * Bias/factuality ratings sourced from AllSides and Media Bias/Fact Check.
 *
 * This module is used both to generate the SQL seed migration and as a
 * runtime reference for the RSS ingestion feed registry (Phase 2b).
 */

import type { DbSourceInsert } from './types'

export const seedSources: DbSourceInsert[] = [
  // -----------------------------------------------------------------------
  // Far Left
  // -----------------------------------------------------------------------
  {
    slug: 'jacobin',
    name: 'Jacobin',
    bias: 'far-left',
    factuality: 'mixed',
    ownership: 'independent',
    url: 'jacobin.com',
    rss_url: 'https://jacobin.com/feed',
    region: 'us',
  },
  {
    slug: 'the-intercept',
    name: 'The Intercept',
    bias: 'far-left',
    factuality: 'high',
    ownership: 'non-profit',
    url: 'theintercept.com',
    rss_url: 'https://theintercept.com/feed/?lang=en',
    region: 'us',
  },
  {
    slug: 'democracy-now',
    name: 'Democracy Now!',
    bias: 'far-left',
    factuality: 'high',
    ownership: 'non-profit',
    url: 'democracynow.org',
    rss_url: 'https://www.democracynow.org/democracynow.rss',
    region: 'us',
  },

  // -----------------------------------------------------------------------
  // Left
  // -----------------------------------------------------------------------
  {
    slug: 'the-guardian',
    name: 'The Guardian',
    bias: 'left',
    factuality: 'high',
    ownership: 'non-profit',
    url: 'theguardian.com',
    rss_url: 'https://www.theguardian.com/us-news/rss',
    region: 'uk',
  },
  {
    slug: 'msnbc',
    name: 'MSNBC',
    bias: 'left',
    factuality: 'mixed',
    ownership: 'corporate',
    url: 'msnbc.com',
    rss_url: 'https://feeds.nbcnews.com/nbcnews/public/news',
    region: 'us',
  },
  {
    slug: 'cnn',
    name: 'CNN',
    bias: 'left',
    factuality: 'mixed',
    ownership: 'corporate',
    url: 'cnn.com',
    rss_url: null,
    is_active: false,
    region: 'us',
  },
  {
    slug: 'the-daily-beast',
    name: 'The Daily Beast',
    bias: 'left',
    factuality: 'mixed',
    ownership: 'corporate',
    url: 'thedailybeast.com',
    rss_url: 'https://www.thedailybeast.com/arc/outboundfeeds/rss/articles/',
    region: 'us',
  },
  {
    slug: 'huffpost',
    name: 'HuffPost',
    bias: 'left',
    factuality: 'mixed',
    ownership: 'corporate',
    url: 'huffpost.com',
    rss_url: 'https://www.huffpost.com/section/front-page/feed',
    region: 'us',
  },

  // -----------------------------------------------------------------------
  // Lean Left
  // -----------------------------------------------------------------------
  {
    slug: 'new-york-times',
    name: 'New York Times',
    bias: 'lean-left',
    factuality: 'high',
    ownership: 'corporate',
    url: 'nytimes.com',
    rss_url: 'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml',
    region: 'us',
  },
  {
    slug: 'washington-post',
    name: 'Washington Post',
    bias: 'lean-left',
    factuality: 'high',
    ownership: 'corporate',
    url: 'washingtonpost.com',
    rss_url: 'https://feeds.washingtonpost.com/rss/national',
    region: 'us',
  },
  {
    slug: 'npr',
    name: 'NPR',
    bias: 'lean-left',
    factuality: 'very-high',
    ownership: 'non-profit',
    url: 'npr.org',
    rss_url: 'https://feeds.npr.org/1001/rss.xml',
    region: 'us',
  },
  {
    slug: 'politico',
    name: 'Politico',
    bias: 'lean-left',
    factuality: 'high',
    ownership: 'corporate',
    url: 'politico.com',
    rss_url: 'https://rss.politico.com/politics-news.xml',
    region: 'us',
  },
  {
    slug: 'abc-news',
    name: 'ABC News',
    bias: 'lean-left',
    factuality: 'high',
    ownership: 'corporate',
    url: 'abcnews.go.com',
    rss_url: 'https://abcnews.go.com/abcnews/topstories',
    region: 'us',
  },
  {
    slug: 'nbc-news',
    name: 'NBC News',
    bias: 'lean-left',
    factuality: 'high',
    ownership: 'corporate',
    url: 'nbcnews.com',
    rss_url: 'https://feeds.nbcnews.com/nbcnews/public/news',
    region: 'us',
  },
  {
    slug: 'cbs-news',
    name: 'CBS News',
    bias: 'lean-left',
    factuality: 'high',
    ownership: 'corporate',
    url: 'cbsnews.com',
    rss_url: 'https://www.cbsnews.com/latest/rss/main',
    region: 'us',
  },
  {
    slug: 'al-jazeera',
    name: 'Al Jazeera',
    bias: 'lean-left',
    factuality: 'high',
    ownership: 'state-funded',
    url: 'aljazeera.com',
    rss_url: 'https://www.aljazeera.com/xml/rss/all.xml',
    region: 'international',
  },
  {
    slug: 'bbc-news',
    name: 'BBC News',
    bias: 'lean-left',
    factuality: 'very-high',
    ownership: 'state-funded',
    url: 'bbc.com',
    rss_url: 'https://feeds.bbci.co.uk/news/rss.xml',
    region: 'uk',
  },
  {
    slug: 'the-atlantic',
    name: 'The Atlantic',
    bias: 'lean-left',
    factuality: 'high',
    ownership: 'corporate',
    url: 'theatlantic.com',
    rss_url: 'https://www.theatlantic.com/feed/all/',
    region: 'us',
  },
  {
    slug: 'vox',
    name: 'Vox',
    bias: 'lean-left',
    factuality: 'high',
    ownership: 'corporate',
    url: 'vox.com',
    rss_url: 'https://www.vox.com/rss/index.xml',
    region: 'us',
  },

  // -----------------------------------------------------------------------
  // Center
  // -----------------------------------------------------------------------
  {
    slug: 'reuters',
    name: 'Reuters',
    bias: 'center',
    factuality: 'very-high',
    ownership: 'corporate',
    url: 'reuters.com',
    rss_url: null,
    is_active: false,
    region: 'international',
  },
  {
    slug: 'ap-news',
    name: 'AP News',
    bias: 'center',
    factuality: 'very-high',
    ownership: 'non-profit',
    url: 'apnews.com',
    rss_url: null,
    is_active: false,
    region: 'us',
  },
  {
    slug: 'pbs-newshour',
    name: 'PBS NewsHour',
    bias: 'center',
    factuality: 'very-high',
    ownership: 'non-profit',
    url: 'pbs.org/newshour',
    rss_url: 'https://www.pbs.org/newshour/feeds/rss/headlines',
    region: 'us',
  },
  {
    slug: 'usa-today',
    name: 'USA Today',
    bias: 'center',
    factuality: 'high',
    ownership: 'corporate',
    url: 'usatoday.com',
    rss_url: null,
    is_active: false,
    region: 'us',
  },
  {
    slug: 'the-hill',
    name: 'The Hill',
    bias: 'center',
    factuality: 'high',
    ownership: 'corporate',
    url: 'thehill.com',
    rss_url: 'https://thehill.com/feed/',
    region: 'us',
  },
  {
    slug: 'axios',
    name: 'Axios',
    bias: 'center',
    factuality: 'high',
    ownership: 'corporate',
    url: 'axios.com',
    rss_url: 'https://api.axios.com/feed/',
    region: 'us',
  },
  {
    slug: 'bloomberg',
    name: 'Bloomberg',
    bias: 'center',
    factuality: 'high',
    ownership: 'corporate',
    url: 'bloomberg.com',
    rss_url: 'https://feeds.bloomberg.com/politics/news.rss',
    region: 'us',
  },
  {
    slug: 'globe-and-mail',
    name: 'The Globe and Mail',
    bias: 'center',
    factuality: 'high',
    ownership: 'corporate',
    url: 'theglobeandmail.com',
    rss_url: 'https://www.theglobeandmail.com/arc/outboundfeeds/rss/category/canada/',
    region: 'canada',
  },
  {
    slug: 'france24',
    name: 'France 24',
    bias: 'center',
    factuality: 'high',
    ownership: 'state-funded',
    url: 'france24.com',
    rss_url: 'https://www.france24.com/en/rss',
    region: 'europe',
  },
  {
    slug: 'dw-news',
    name: 'DW News',
    bias: 'center',
    factuality: 'very-high',
    ownership: 'state-funded',
    url: 'dw.com',
    rss_url: 'https://rss.dw.com/rdf/rss-en-all',
    region: 'europe',
  },

  // -----------------------------------------------------------------------
  // Lean Right
  // -----------------------------------------------------------------------
  {
    slug: 'wall-street-journal',
    name: 'Wall Street Journal',
    bias: 'lean-right',
    factuality: 'high',
    ownership: 'corporate',
    url: 'wsj.com',
    rss_url: 'https://feeds.a.dj.com/rss/RSSWorldNews.xml',
    region: 'us',
  },
  {
    slug: 'the-economist',
    name: 'The Economist',
    bias: 'lean-right',
    factuality: 'very-high',
    ownership: 'corporate',
    url: 'economist.com',
    rss_url: 'https://www.economist.com/international/rss.xml',
    region: 'uk',
  },
  {
    slug: 'forbes',
    name: 'Forbes',
    bias: 'lean-right',
    factuality: 'high',
    ownership: 'corporate',
    url: 'forbes.com',
    rss_url: 'https://www.forbes.com/news/feed2/',
    region: 'us',
  },
  {
    slug: 'reason',
    name: 'Reason',
    bias: 'lean-right',
    factuality: 'high',
    ownership: 'non-profit',
    url: 'reason.com',
    rss_url: 'https://reason.com/feed/',
    region: 'us',
  },
  {
    slug: 'realclearpolitics',
    name: 'RealClearPolitics',
    bias: 'lean-right',
    factuality: 'high',
    ownership: 'independent',
    url: 'realclearpolitics.com',
    rss_url: 'https://www.realclearpolitics.com/index.xml',
    region: 'us',
  },
  {
    slug: 'the-dispatch',
    name: 'The Dispatch',
    bias: 'lean-right',
    factuality: 'very-high',
    ownership: 'independent',
    url: 'thedispatch.com',
    rss_url: 'https://thedispatch.com/feed/',
    region: 'us',
  },
  {
    slug: 'financial-times',
    name: 'Financial Times',
    bias: 'lean-right',
    factuality: 'very-high',
    ownership: 'corporate',
    url: 'ft.com',
    rss_url: 'https://www.ft.com/?format=rss',
    region: 'uk',
  },
  {
    slug: 'the-telegraph',
    name: 'The Telegraph',
    bias: 'lean-right',
    factuality: 'high',
    ownership: 'corporate',
    url: 'telegraph.co.uk',
    rss_url: 'https://www.telegraph.co.uk/rss.xml',
    region: 'uk',
  },

  // -----------------------------------------------------------------------
  // Right
  // -----------------------------------------------------------------------
  {
    slug: 'fox-news',
    name: 'Fox News',
    bias: 'right',
    factuality: 'mixed',
    ownership: 'corporate',
    url: 'foxnews.com',
    rss_url: 'https://moxie.foxnews.com/google-publisher/latest.xml',
    region: 'us',
  },
  {
    slug: 'national-review',
    name: 'National Review',
    bias: 'right',
    factuality: 'mixed',
    ownership: 'independent',
    url: 'nationalreview.com',
    rss_url: 'https://www.nationalreview.com/feed/',
    region: 'us',
  },
  {
    slug: 'new-york-post',
    name: 'New York Post',
    bias: 'right',
    factuality: 'mixed',
    ownership: 'corporate',
    url: 'nypost.com',
    rss_url: 'https://nypost.com/feed/',
    region: 'us',
  },
  {
    slug: 'daily-wire',
    name: 'Daily Wire',
    bias: 'right',
    factuality: 'mixed',
    ownership: 'independent',
    url: 'dailywire.com',
    rss_url: 'https://www.dailywire.com/feeds/rss.xml',
    region: 'us',
  },
  {
    slug: 'washington-times',
    name: 'Washington Times',
    bias: 'right',
    factuality: 'mixed',
    ownership: 'independent',
    url: 'washingtontimes.com',
    rss_url: 'https://www.washingtontimes.com/rss/headlines/news/',
    region: 'us',
  },
  {
    slug: 'daily-mail',
    name: 'Daily Mail',
    bias: 'right',
    factuality: 'low',
    ownership: 'corporate',
    url: 'dailymail.co.uk',
    rss_url: 'https://www.dailymail.co.uk/articles.rss',
    region: 'uk',
  },
  {
    slug: 'washington-examiner',
    name: 'Washington Examiner',
    bias: 'right',
    factuality: 'mixed',
    ownership: 'corporate',
    url: 'washingtonexaminer.com',
    rss_url: 'https://www.washingtonexaminer.com/feed',
    region: 'us',
  },
  {
    slug: 'the-federalist',
    name: 'The Federalist',
    bias: 'right',
    factuality: 'mixed',
    ownership: 'independent',
    url: 'thefederalist.com',
    rss_url: 'https://thefederalist.com/feed/',
    region: 'us',
  },
  {
    slug: 'sky-news-australia',
    name: 'Sky News Australia',
    bias: 'right',
    factuality: 'mixed',
    ownership: 'corporate',
    url: 'skynews.com.au',
    rss_url: null,
    is_active: false,
    region: 'international',
  },

  // -----------------------------------------------------------------------
  // Far Right
  // -----------------------------------------------------------------------
  {
    slug: 'breitbart',
    name: 'Breitbart',
    bias: 'far-right',
    factuality: 'low',
    ownership: 'independent',
    url: 'breitbart.com',
    rss_url: 'https://feeds.feedburner.com/breitbart',
    region: 'us',
  },
  {
    slug: 'the-blaze',
    name: 'The Blaze',
    bias: 'far-right',
    factuality: 'mixed',
    ownership: 'independent',
    url: 'theblaze.com',
    rss_url: 'https://www.theblaze.com/feeds/feed.rss',
    region: 'us',
  },
  {
    slug: 'the-epoch-times',
    name: 'The Epoch Times',
    bias: 'far-right',
    factuality: 'mixed',
    ownership: 'independent',
    url: 'theepochtimes.com',
    rss_url: 'https://feed.theepochtimes.com/us/feed',
    region: 'us',
  },
  {
    slug: 'oann',
    name: 'One America News',
    bias: 'far-right',
    factuality: 'low',
    ownership: 'independent',
    url: 'oann.com',
    rss_url: 'https://www.oann.com/feed/',
    region: 'us',
  },
  {
    slug: 'newsmax',
    name: 'Newsmax',
    bias: 'far-right',
    factuality: 'low',
    ownership: 'corporate',
    url: 'newsmax.com',
    rss_url: null,
    is_active: false,
    region: 'us',
  },

  // -----------------------------------------------------------------------
  // International / Regional (various biases)
  // -----------------------------------------------------------------------
  {
    slug: 'cbc-news',
    name: 'CBC News',
    bias: 'lean-left',
    factuality: 'high',
    ownership: 'state-funded',
    url: 'cbc.ca',
    rss_url: 'https://rss.cbc.ca/lineup/topstories.xml',
    region: 'canada',
  },
  {
    slug: 'national-post',
    name: 'National Post',
    bias: 'lean-right',
    factuality: 'high',
    ownership: 'corporate',
    url: 'nationalpost.com',
    rss_url: 'https://nationalpost.com/feed',
    region: 'canada',
  },
  {
    slug: 'der-spiegel',
    name: 'Der Spiegel',
    bias: 'lean-left',
    factuality: 'high',
    ownership: 'corporate',
    url: 'spiegel.de',
    rss_url: 'https://www.spiegel.de/international/index.rss',
    region: 'europe',
  },
  {
    slug: 'sky-news',
    name: 'Sky News',
    bias: 'lean-right',
    factuality: 'high',
    ownership: 'corporate',
    url: 'news.sky.com',
    rss_url: 'https://feeds.skynews.com/feeds/rss/home.xml',
    region: 'uk',
  },
]

/**
 * Total count of seed sources — useful for assertions in tests.
 */
export const SEED_SOURCE_COUNT = seedSources.length
